function set_script_parameters(accel_speed, climb_alt, levelturn_hdg, climbturn_alt, ...
    climbturn_hdg, descturn_alt, descturn_hdg, hldpat_hdg, hldpat_timer, ...
    takeoff_pitch, takeoff_thr, takeoff_speed, takeoff_alt, lndg_speed)

    % add element at beginning, which will be interpreted as timeseries
    % data by the "From Workspace" block and discarded from the array.

    arr = [-999, accel_speed, climb_alt, levelturn_hdg, climbturn_alt, ...
    climbturn_hdg, descturn_alt, descturn_hdg, hldpat_hdg, hldpat_timer, ...
    takeoff_pitch, takeoff_thr, takeoff_speed, takeoff_alt, lndg_speed];

    assignin('base', "script_parameters", arr);
end