function store_anomaly_params_json(inj_type, startt, endt, val, sensor, type, coef1, coef2, freq)
    anomalyStr = append('{"Injection": {"InjectionType": ', int2str(inj_type), ...
        ',"StartTime": ', sprintf('%.2f', startt), ...
        ',"EndTime": ', sprintf('%.2f', endt), ...
        ',"Val": ', sprintf('%.2f', val), ...
        ',"Sensor Index": ', int2str(sensor), ...
        ',"Type": ', int2str(type), ...
		',"Coef1": ', int2str(coef1), ...
		',"Coef2": ', int2str(coef2), ...
		',"Freq": ', sprintf('%.2f', freq), ...
		',"Percentile": 0}}');

    params_table = struct2table(jsondecode(anomalyStr).Injection);
    sorted_params_struct = table2struct(sortrows(params_table, 'StartTime'));
    

    
    assignin('base', "sortedParams", sorted_params_struct);

    assignin('base', 'anom_param_bus', Simulink.Bus.createObject(sorted_params_struct));
end
